### ISSUE TITLE
Unable to set buyerDetails and NotifyURL

### ISSUE THREAD

**Issue by shellprog** [thephpleague/omnipay-bitpay#2]
Hi ,
I am not able to set notifyurl . When invoice is created i got a response which contains invoice url but address is not shown so i was not even able to set address . I tried following 

```
$invoice_arr = [ 'amount' => '10.00',
            'currency' => 'USD',
            'transactionId' => '1',
            'description' => 'Product description',
            'notifyUrl' => 'https://www.kodeinfo.com/notify',
            'notifyEmail' => 'someemail@gmail.com',
            'returnUrl' => 'https://www.kodeinfo.com/return',
            "buyerName"=>"Imran","buyerAddress1"=>"Rein bazar",
            "buyerAddress2"=>"Rein bazar","buyerCity"=>"Hyderabad",
            "buyerState"=>"AP","buyerZip"=>"500023",
            "buyerCountry"=>"India","buyerEmail"=>"someemail@gmail.com",
            "buyerPhone"=>"mobileno"];
```

and also

```
        $card = new \Omnipay\Common\CreditCard();
        $card->setName('Imran');
        $card->setAddress1('Rein Bazar');
        $card->setAddress2('');
        $card->setCity('Hyderabad');
        $card->setState('Telangana');
        $card->setPostcode('500023');
        $card->setCountry('India');
        $card->setEmail('someemail@gmail.com');
        $card->setPhone('mobileno');


$invoice_arr = [ 'amount' => '10.00',
            'currency' => 'USD',
            'transactionId' => '1',
            'description' => 'Product description',
            'notifyUrl' => 'https://www.kodeinfo.com/notify',
            'notifyEmail' => 'someemail@gmail.com',
            'returnUrl' => 'https://www.kodeinfo.com/return',
            'card'=>$card];
```

unable to set fullnotifications and not getting any email when invoice expires

Thanks for your package

**Comment by vercotux** [comment]
I had a similar issue with not getting any IPN notifications. My development server was locked with HTTP Basic Authentication so BitPay was unable to send the notification request - even when I added username:password to _notifyUrl_! I had to remove password protection from the host to make it work.

There are also certain other requirements to make it work.
See [IPN Troubleshooting](https://bitpay.com/docs/invoice-callbacks).

**Comment by nfodev** [comment]
Hi there,

I also need to set the fullNotifications, and i can't seem to find a workaround. Can someone help me with this?

Thanks for your work!

Bert

Edit: Actually I just found out how to do it. See **"Omnipay now also supports modifying request data before it is sent to the gateway."** on the bottom of this page: http://omnipay.thephpleague.com/changelog/

```
    /** @var \Omnipay\BitPay\Message\PurchaseRequest $request */
    $request = $this->getGateway()->purchase($parameters);

    // Add custom parameter (not supported by gateway).
    $data = $request->getData();
    $data['fullNotifications'] = true;

    try {
        /** @var \Omnipay\BitPay\Message\PurchaseResponse $response */
        $response = $request->sendData($data);
    } catch (\Exception $e) {..
```
