### ISSUE TITLE
PurchaseResponse.php: "Undefined index: messages"

### ISSUE THREAD

**Issue by vercotux** [thephpleague/omnipay-bitpay#4]
It appears the error message structure has changed and is causing an exception at [PurchaseResponse.php#L26](https://github.com/thephpleague/omnipay-bitpay/blob/e6d6476147bcd9adc6fd1ee02bfbdc33d702dc76/src/Message/PurchaseResponse.php#L26) whenever BitPay returns an error:

> Undefined index: messages

This is what was in `$this->['data']` according to _print_r_:

```
Array ( [type] => limitExceeded [message] => Invoice not created due to account limits, please check your approval levels ) 
```

**Comment by delatbabel** [comment]
Noted. Any chance of a PR?

**Comment by vercotux** [comment]
Yes. Here we go: #5

**Comment by delatbabel** [comment]
Merged, with thanks.
